.TH dbk-strip 1
.SH NAME    \" Section header
.PP

dbk-strip \- Remove content, leaving only chapter and section frames

\" Convention:
\" Underline anything that is typed verbatim - commands, etc.
.SH SYNOPSIS
.PP
.nf 
.na
dbk-strip < inpput.dbk > output.dbk
.ad
.fi

.SH "DESCRIPTION"

The
.B dbk-strip
command removes all content from a docbook XML file, leaving only the
chapter and section frames.  This is useful for generating answer keys
or abreviated notes based on a large document.

.SH "SEE ALSO"
\" List related commands here

.SH BUGS
Please report bugs to the author and send patches in unified diff format.
(man diff for more information)

.SH AUTHOR
.nf
.na
J. Bacon
