#!/bin/sh -e

##########################################################################
#   Synopsis:
#       
#   Description:
#       
#   Arguments:
#       
#   Returns:
#
#   Examples:
#
#   Files:
#
#   Environment:
#
#   See also:
#       
#   History:
#   Date        Name        Modification
#   2022-08-29  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 file.dbk [file.dbk ...]\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# -lt 1 ]; then
    usage
fi

rm -rf Key
mkdir -p Key
for file in "$@"; do
    dir=$(dirname $file)
    base=$(basename $file)
    hw_file=Key/$base
    # Remove content from included chapters and replace HW/ with Key/
    # so includes pull the HW file with answers visible.  Answers are
    # embedded with <info> tags in the main file so they are not displayed
    # in the text.
    # echo $file
    dbk-strip < $file | sed -e 's|HW/||g' > $hw_file

    # Generate HW files with answers visible by replacing <info> with <para>
    # Store in temporary Key directory
    for hw_file in $dir/HW/*.dbk; do
	# echo $hw_file
	key_file=Key/$(basename $hw_file)
	sed -e 's|info>|para>|g' $hw_file > $key_file
    done
done

cd Key
cp ../practice-key.dbk .
dbk-genmake practice-key.dbk *.dbk
make pdf
mv practice-key.pdf ..

