#!/bin/sh -e

##########################################################################
#   Synopsis:
#       
#   Description:
#       
#   Arguments:
#       
#   Returns:
#
#   Examples:
#
#   Files:
#
#   Environment:
#
#   See also:
#       
#   History:
#   Date        Name        Modification
#   2022-08-29  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 file.dbk [file.dbk ...]\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# -lt 1 ]; then
    usage
fi

for file in "$@"; do
    echo $file
    dbk-strip < $file > HW/$file
done

mkdir -p Key
for file in HW/*.dbk; do
    sed -e 's|info>|para>|g' $file > Key/`basename $file`
done
cd Key
dbk-genmake ../practice-key.dbk *.dbk ../Programs/*.dbk
make pdf
docviewer ../practice-key.pdf
cd ..
rm -rf Key
